# Generated by Django 5.2.11 on 2026-03-12 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stantions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TariffModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("price_per_tick", models.PositiveIntegerField(null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "tariff_type",
                    models.CharField(
                        choices=[
                            ("PER_MINUTE", "Per Minute"),
                            ("PER_HOUR", "Per Hour"),
                            ("PER_DAY", "Per Day"),
                            ("FIXED", "Fixed"),
                        ],
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="RentalModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("final_price", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIALIZING", "Initializing"),
                            ("ACTIVE", "Active"),
                            ("WAIT_FOR_COMPLETION", "Wait for completion"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=255,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "battery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rentals",
                        to="stantions.registeredbatterymodel",
                    ),
                ),
                (
                    "completed_at_stantion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rentals_as_end",
                        to="stantions.registeredstantionmodel",
                    ),
                ),
                (
                    "related_accept_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rental_accept",
                        to="stantions.stantiontaskmodel",
                    ),
                ),
                (
                    "related_release_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rental",
                        to="stantions.stantiontaskmodel",
                    ),
                ),
                (
                    "started_at_stantion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rentals_as_start",
                        to="stantions.registeredstantionmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rentals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tariff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rentals",
                        to="rentals.tariffmodel",
                    ),
                ),
            ],
        ),
    ]
