# Generated by Django 5.2.11 on 2026-03-11 11:30

import server.apps.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="usermodel",
            managers=[
                ("objects", server.apps.users.models.UserModelManager()),
            ],
        ),
    ]
