# Generated by Django 5.2.11 on 2026-03-12 00:07

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models

import server.common.name_generator


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BatteryTypeModel",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RegisteredStantionModel",
            fields=[
                (
                    "hardware_id",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default=server.common.name_generator.generate_name,
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="StantionTypeModel",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("max_slots", models.PositiveSmallIntegerField()),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RegisteredBatteryModel",
            fields=[
                (
                    "hardware_id",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "battery_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batteries",
                        to="stantions.batterytypemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StantionHeartBeatModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "registered_stantion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="heartbeats",
                        to="stantions.registeredstantionmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HeartBeatSlotStateModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("charged", "Charged"),
                            ("charging", "Charging"),
                            ("empty", "Empty"),
                        ]
                    ),
                ),
                ("slot_index", models.PositiveSmallIntegerField()),
                (
                    "registered_battery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stantions.registeredbatterymodel",
                    ),
                ),
                (
                    "heartbeat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slot_states",
                        to="stantions.stantionheartbeatmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StantionTaskModel",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("release_battery", "Release Battery"),
                            ("receive_battery", "Receive Battery"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("reserved", "Reserved"),
                            ("accepted", "Accepted"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                            ("failed", "Failed"),
                        ],
                        default="created",
                        max_length=255,
                    ),
                ),
                ("response_release_battery_error", models.TextField(blank=True)),
                ("response_release_battery_success", models.BooleanField(null=True)),
                ("response_receive_battery_error", models.TextField(blank=True)),
                ("response_receive_battery_success", models.BooleanField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expiring_after", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payload_release_battery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payload_release_battery_tasks",
                        to="stantions.registeredbatterymodel",
                    ),
                ),
                (
                    "response_release_battery_battery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payload_receive_battery_tasks",
                        to="stantions.registeredbatterymodel",
                    ),
                ),
                (
                    "to_stantion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stantions.registeredstantionmodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="registeredstantionmodel",
            name="stantion_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stantions",
                to="stantions.stantiontypemodel",
            ),
        ),
        migrations.AddField(
            model_name="batterytypemodel",
            name="compatipable_with_stantions",
            field=models.ManyToManyField(
                related_name="compatipable_batterry_types",
                to="stantions.stantiontypemodel",
            ),
        ),
    ]
