# Generated by Django 5.2.11 on 2026-03-12 04:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stantions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stantiontaskmodel",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
