# Generated by Django 5.2.11 on 2026-03-11 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stantions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batterytypemodel",
            name="id",
        ),
        migrations.RemoveField(
            model_name="registeredbatterymodel",
            name="id",
        ),
        migrations.RemoveField(
            model_name="registeredstantionmodel",
            name="id",
        ),
        migrations.RemoveField(
            model_name="stantiontypemodel",
            name="id",
        ),
        migrations.AlterField(
            model_name="batterytypemodel",
            name="name",
            field=models.CharField(
                max_length=255, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="heartbeatslotstatemodel",
            name="heartbeat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slot_states",
                to="stantions.stantionheartbeatmodel",
            ),
        ),
        migrations.AlterField(
            model_name="heartbeatslotstatemodel",
            name="registered_battery",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="stantions.registeredbatterymodel",
            ),
        ),
        migrations.AlterField(
            model_name="registeredbatterymodel",
            name="hardware_id",
            field=models.CharField(
                max_length=255, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="registeredstantionmodel",
            name="hardware_id",
            field=models.CharField(
                max_length=255, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="stantionheartbeatmodel",
            name="registered_stantion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="heartbeats",
                to="stantions.registeredstantionmodel",
            ),
        ),
        migrations.AlterField(
            model_name="stantiontaskmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("reserved", "Reserved"),
                    ("accepted", "Accepted"),
                    ("completed", "Completed"),
                    ("expired", "Expired"),
                    ("failed", "Failed"),
                ],
                default="created",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="stantiontaskmodel",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("release_battery", "Release Battery"),
                    ("receive_battery", "Receive Battery"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="stantiontypemodel",
            name="name",
            field=models.CharField(
                max_length=255, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
